### ISSUE TITLE
qiniu-upload-plugin@1.2.8安装报错

### ISSUE THREAD

**Issue by RongleXie** [yhlben/cdfang-spider#25]
![TIM截图20190628223345](https://user-images.githubusercontent.com/14212979/60349957-1e8b6580-99f5-11e9-8ea2-5122d013d449.png)

执行**npm i**安装报错，单独执行**npm install qiniu-upload-plugin**也无法安装。

**Comment by yhlben** [comment]
@RongleXie  刚我测试了以下情况，并未发现由此问题。

- 本地连代理
- 本地不连代理
- 服务器上安装

你遇到的情况可能是因为 npm 暂时挂了，可以删除 package-lock.json 和 node_modules 文件后再次尝试以下。

**Comment by RongleXie** [comment]
@yhlben 不清楚是不是我网络的原因，我挂代理和不挂代理都没法直接安装这个包。但是我先把**qiniu-upload-plugin**的两个依赖包先安装上，后面安装它就正常了。
1. **npm install ora**
2. **npm install qiniu**
3. **npm i qiniu-upload-plugin**

**Comment by yhlben** [comment]
@RongleXie 经 github 提示，发现  ora@3.0.0 中的依赖包中有漏洞隐患，目前已经更新了依赖包，可以试试 qiniu-upload-plugin@1.2.9，可能是这个问题引起的。

**Comment by RongleXie** [comment]
@yhlben qiniu-upload-plugin@1.2.9 可以直接安装了哈，感谢楼主。
