### ISSUE TITLE
只有UI?

### ISSUE THREAD

**Issue by hookover** [yhlben/cdfang-spider#27]
rt

**Comment by yhlben** [comment]
@hookover  你好，ui 和数据都有哦，并且是实时同步最新的数据。[访问地址](https://cdfangyuan.cn)

**Comment by hookover** [comment]
> @hookover 你好，ui 和数据都有哦，并且是实时同步最新的数据。[访问地址](https://cdfangyuan.cn)

抱歉啦，没有看到爬虫代码呢，数据实际从其它地方获取的？

**Comment by yhlben** [comment]
@hookover 爬虫代码在 `src/nodeuii/utils/spiderHelper.ts` 文件。

**Comment by hookover** [comment]
@yhlben 谢谢啦
